lava/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    picture = FileField('Picture of post',
        validators=[ FileAllowed(['jpg', 'png','jpeg','tiff']),DataRequired()])
    submit = SubmitField('Post')

lava/map/__init__.py
from flask import render_template, Blueprint

map = Blueprint('map', __name__)

@map.route('/map')
def maps():
    return render_template('map.html')

lava/posts/routes.py
from unicodedata import category
from flask import (render_template,
    url_for,
    flash,
    redirect,
    Blueprint,
    request
    )
from flask_login import current_user, login_required
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from lava import db
from lava.models import Post,Comment
from lava.posts.forms import PostForm
from lava.utils import save_picture



posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        # if form.picture.data:
            # picture_file = save_picture(form.picture.data)
            # current_user.image_file = picture_file
            # print('form data',form.picture)

        picture_file = save_picture(form.picture.data)
        current_user.image_file = picture_file
        # picture_file = 'default.jpg'
        post = Post(title=form.title.data,
            content=form.content.data,image=picture_file, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been Created!', category='success')
        return redirect(url_for('main.index'))
    return render_template('create_post.html',
        title='New Post', form=form, legend='Post')


@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route('/create_comment/<int:post_id>', methods=['POST'])
@login_required
def create_comment(post_id):
    post = Post.query.filter_by(id=post_id)
    if not post:
        flash("Post does not exist!",category='danger')
        return redirect(url_for('main.index'))
    else:
        content = request.form.get('text')
        if content is None:
            flash("Please enter something!",category='danger')
            return redirect(url_for('posts.post',post_id=post_id))
        else:
            comment = Comment(content=content,
                author=current_user,post_id=post_id)
            db.session.add(comment)
            db.session.commit()
    return redirect(url_for('posts.post',post_id=post_id))


@posts.route('/post_up/<int:post_id>', methods=['POST','GET'])
@login_required
def up_vote(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if not post:
        flash("Post does not exist!",category='danger')
        return redirect(url_for('main.index'))
    else:
        post.up = post.up + 1
        db.session.commit()
    return redirect(url_for('posts.post',post_id=post_id))


@posts.route('/post_down/<int:post_id>', methods=['POST','GET'])
@login_required
def down_vote(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if not post:
        flash("Post does not exist!",category='danger')
        return redirect(url_for('main.index'))
    else:
        post.down = post.down + 1
        db.session.commit()
    return redirect(url_for('posts.post',post_id=post_id))

lava/todo/__init__.py
from flask import render_template, Blueprint

todo = Blueprint('todo', __name__)

@todo.route('/ycd')
def ycd():
    return render_template('youcando.html')

@todo.route('/clean_air')
def clean_air():
    return render_template('clean_air.html')

lava/users/routes.py
from asyncio import run_coroutine_threadsafe
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from lava.users.forms import RegistatonForm, LoginForm
from lava import db,bcrypt
from lava.models import User,Post

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash(f'You are alread logged in!', 'success')
        return redirect(url_for('main.index'))
    form = RegistatonForm()
    if form.validate_on_submit():
        hashed_pass = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(name=form.name.data,
                    email=form.email.data, password=hashed_pass,gender=form.gender.data,date=form.b_date.data)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created. You can login now!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash(f'You are alread logged in!', 'success')
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            # redirect ot next pager
            next_page = request.args.get('next')
            flash(f'You have successufily logged in!', 'success')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('main.index'))
        else:
            flash(f'Login unsuccessful, please email & password info', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    flash(f'You have successufily logged out!', 'success')
    return redirect(url_for('main.index'))

lava/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap 5 CSS -->
    <!-- <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->

    <!-- Bootstrap 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link
    rel="stylesheet"
    type="text/css"
    href="{{ url_for('static', filename='style/style.css') }}"
    >

    
    <!-- Our title chooser -->
    {% if title %}
        <title>Lava - {{ title }}</title>
    {% else %}
        <title>Lava</title>
    {% endif %}
</head>
<body>
    <!-- top navigation bar  -->
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-green fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Lava</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a
                class="nav-item nav-link"
                href="{{url_for('map.maps')}}">
                Map
              </a>
              <a 
                class="nav-item nav-link"
                href="{{url_for('todo.ycd')}}">
                YouCanDo
              </a>
              <a 
                class="nav-item nav-link"
                href="{{url_for('todo.clean_air')}}">
                CleanAir
              </a>
            </div>
              <!-- Navbar Right Side -->
            <div class="navbar-nav ms-auto">
              {% if current_user.is_authenticated %}
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('posts.new_post')}} ">
                  Create
                </a>
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('users.logout')}} ">
                  Logout
                </a>
              {% else %}
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('users.login')}} ">
                  Login
                </a>
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('users.register')}} ">
                  Join
                </a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
   
    <main role="main" class="container body-content">
      <div class="row">
        <!-- issue/post content -->
        <div class="col-md-8 center">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </main>


    <!-- js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

lava/templates/base_index.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link
    rel="stylesheet"
    type="text/css"
    href="{{ url_for('static', filename='style/style.css') }}"
    >
    
    <!-- Our title chooser -->
    {% if title %}
        <title>Lava - {{ title }}</title>
    {% else %}
        <title>Lava</title>
    {% endif %}
</head>
<body>
    <!-- top navigation bar  -->
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-green fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Lava</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a
                class="nav-item nav-link"
                href="{{url_for('map.maps')}}">
                Map
              </a>
              <a 
                class="nav-item nav-link"
                href="{{url_for('todo.ycd')}}">
                YouCanDo
              </a>
              <a 
                class="nav-item nav-link"
                href="{{url_for('todo.clean_air')}}">
                CleanAir
              </a>
            </div>
              <!-- Navbar Right Side -->
            <div class="navbar-nav ms-auto d-flex justify-content-between">
              {% if current_user.is_authenticated %}
                <!-- create a new post-->
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('posts.new_post')}} ">
                  Create
                </a>
                <!-- view user posts -->
                <a
                  class="nav-item nav-link"
                  href="#">
                  User Posts
                </a>
                <!-- logged out of a session-->
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('users.logout')}} ">
                  Logout
                </a>
              {% else %}
                <!-- login -->
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('users.login')}} ">
                  Login
                </a>
                <!-- register -->
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('users.register')}} ">
                  Join
                </a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
   
    <main role="main" class="container body-content">
      <div class="row">
        <!-- issue/post content -->
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
        {% endwith %}
          {% block content %}
          {% endblock %}
        </div>
        <!-- sidebar for additional/custom query -->
        <div class="col-md-4">
          <div class="content-overview">
            <h3>Overview</h3>
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">
                  Most recent</li>
                <li
                class="list-group-item list-group-item-light">
                Most vote</li>
              </ul>
              <img src="https://picsum.photos/200" alt="img">
          </div>
        </div>
      </div>
    </main>


    <!-- js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

lava/templates/clean_air.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   
    <title>Clean Air</title>
    <link
    rel="stylesheet"
    type="text/css"
    href="{{ url_for('static', filename='style/ycd.css') }}"
    >
</head>
<body style="background-color:hsl(106, 85%, 80%) ; text-align:justify ;">


<img src="https://cff2.earth.com/uploads/2016/11/03135030/clean-air-pollution_1big_stokc.jpg" height="600" width="1600" alt="">
 <p><h2>An action plan for clean air and better health</h2></p> 
 <p>Air pollution is a massive threat to health and wellbeing across the WHO South-East Asia Region. We can change that.

    Cancer. Stroke. Heart Disease. Asthma.
    
    These are some of the life-threatening diseases caused by air pollution, a problem that kills more than six million people worldwide every year and which is the most pressing environmental health risk humanity faces. In 98% of cities in low- and middle-income countries air quality exceeds WHO safe-levels and is having a severe impact on health. The youngest, oldest and poorest among us are most affected.
    
    For urban residents across the South-East Asia Region the situation is dire. As urbanization proceeds, inadequate planning is compounding an already fraught scenario. Every day, more and more people are exposed to the deadly particulates motor vehicles, diesel generators, smokestacks and power plants pump out. And every day, those particulates are having a devastating impact on our immediate and long-term health.
    
    Despite the magnitude of the problem, change is possible. Each one of us can do our part.
    
    Choosing to take public transport over driving a private vehicle is a good way to make an immediate difference that not only decreases emissions, but also saves money and encourages physical activity. Similarly, if and when we do use a private vehicle we can ensure that its engine is well-tuned and running efficiently, thereby decreasing emissions and maximizing fuel mileage. Though these steps are simple, they can have wide-ranging impact: Private vehicle use remains a significant contributor to urban air pollution across the Region.
    
    In and around the home we can also make small but important changes. Instead of burning wood and other biomass fuels for cooking or heating, for example, we can switch to using natural gas or liquefied petroleum gas (LPG). The household use of wood and other biomass fuels (including kerosene) is the cause of approximately 1.69 million deaths can also make concerted efforts to cut down on and better dispose of waste, including by ending open burning.
    
    In aiding private citizens’ actions, government interventions can be of crucial importance.
    
    It is now being seen across the Region that from the municipal level up, governments are aiming to provide the infrastructure needed to provide healthier environments and taking steps to encourage public forms of transport. This is being done by building quality bus and rail systems, and by making cities pedestrian- and bicycle-friendly through the provision of footpaths and bicycle lanes. Schemes are being implemented to provide incentives for households to switch to cleaner energy sources that are benefiting the poor and vulnerable. Biomass continues to be burned largely as a result of cost incentives and there is realization now that demand can be shifted to other forms of household energy through subsidies and other innovative pricing mechanisms.
    
    Empowering and engaging the health sector is also important. Not only can the health sector identify and assist vulnerable groups to prevent exposure to air pollution, thereby mitigating its effects, but it can also provide critical support to the society-wide struggle for clean air. Health institutions and workers have the power to raise awareness and promote change at the personal and policy levels – a role that should be encouraged and where possible supported.
    
    As part of this wider push, cities across the Region are urged to join the Breathe Life 2030 campaign, a WHO-lead effort to mobilize individuals and the cities they live in to take action against air pollution. More than 30 cities have already joined, and are working from the grassroots up to achieve cleaner air, improved health and a greener environment. All cities and towns in the South-East Asia Region could also benefit from / or the opportunity to do likewise.
    
    That opportunity should be welcomed. Though air pollution represents a massive moral and practical challenge, it also represents a chance to chart a bold new path – one where clean air is an integral part of healthy economic development and growth. Indeed, as countries across the South-East Asia Region develop and prosper, they needn’t repeat the development tropes of a bygone era. They can and must write a different history.
    
    </p>      



    <!-- footer strt -->
    <div class="footer">
        <div class="wrapper">
            <div class="footer_nav">
                <ul>
                    <li>Home</li></a></li>
                    <li>|</li>
                    <li>About Us</li>
                    <li>|</li>
                    <li>Solutions</li>

                    
                    <li>|</li>
                    <li>Contract Us</li>
               
                 <p>Copyright@2022.pythonic_lava,Inc.All Rights Reserved</p>
                </ul>
            </div>
            
        </div>
    </div>
    <!-- footer end -->

</body>
</html>

lava/templates/index.html
{% extends "base_index.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <div class="media-body">
            <div class="vote">
              <div class="up">
                <a href="#">
                👆{{post.up}}
                </a>
              </div>
              <div class="down">
                <a href="#">
                👇{{post.down}}
                </a>
              </div>
            </div>
            <div class="article-metadata">
              <a class="mr-2" href="#">{{post.author.name}}</a>
              <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
            </div>
            <h2>
              <a class="article-title" href="{{ url_for('posts.post',post_id=post.id) }}">{{post.title}}</a>
            </h2>
            <p class="article-content">{{post.content}}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

lava/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
      <form method="POST" action="">
        {{ form.hidden_tag() }}

        <fieldset>
          <legend class="border-buttom mb-4">Enter</legend>
          <div class="form-group">
            {{ form.email.label(class="form-control-label")}}
            {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid")}}
              <div class="invalid-feedback">
                {% for error  in form.email.errors %}
                  <span>{{error}}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.email(class="form-control form-control-lg")}}
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.password.label(class="form-control-label")}}
            {% if form.password.errors %}
              {{ form.password(class="form-control form-control-lg is-invalid")}}
              <div class="invalid-feedback">
                {% for error  in form.password.errors %}
                  <span>{{error}}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.password(class="form-control form-control-lg")}}
            {% endif %}

            <div class="form-check">
              {{ form.remember(class="form-check-input")}}
              {{ form.remember.label(class="form-check-label")}}
            </div>
          </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class='btn btn-outline-info')}}
        </div>
      </form>
     <div class="border-top pt-3">
       <small class='text-muted'>
         Need an account?
         <a class="ml-2" href="{{ url_for('users.register')}}">Signup Now</a>
       </small>
     </div>
    </div>
{% endblock content %}

lava/templates/post.html
{% extends "base.html" %}
{% block content %}

  <div>
      <article class="media content-section">
        <div class="media-body">
          <div class="vote">
            <div class="up">
              <a href="{{ url_for('posts.up_vote',post_id=post.id)}}">
              👆{{post.up}}
              </a>
            </div>
            <div class="down">
              <a href="{{ url_for('posts.down_vote',post_id=post.id)}}">
              👇{{post.down}}
              </a>
            </div>
          </div>
          <div class="article-metadata">
            <a class="mr-2" href="#">{{post.author.name}}</a>
            <small class="text-muted">{{post.date_posted.strftime('%Y-%m-%d')}}</small>
          </div>
          <h2>
            <a class="article-title" href="{{ url_for('posts.post',post_id=post.id) }}">{{post.title}}</a>
          </h2>
          <p class="article-content">{{post.content}}</p>
        <img
          class="article-img img-thumbnail"
          src="{{ url_for('static', filename='media/' + post.image) }}"
          alt="Post Image"
        >
        </div>
      </article>
  </div>
  <!-- comment areas -->
  <div>
    <form
      class="input-group"
      method="POST"
      action="/create_comment/{{post.id}}"
    >
      <input
        type="text"
        id="text"
        name="text"
        class="form-control"
        placeholder="Comment"/>
      <button 
        type="submit"
        clas="btn btn-primary">
        Submit
      </button>
    </form>
  </div>

  <!-- showing comments -->
  <div>
      {% for comment in post.comments %}
        <div>
          </p>{{comment.content}}</p> 
          <small>by <i>{{comment.author.name}}</i></small>
        </div>
      {% endfor %}
  </div>
{% endblock content %}

lava/templates/youcando.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   
    <title>Your Todo</title>

    <link
    rel="stylesheet"
    type="text/css"
    href="{{ url_for('static', filename='style/ycd.css') }}"
    >

    <!-- Bootstrap CSS -->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>

    <!-- top navigation bar  -->
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-green fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Lava</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a
                class="nav-item nav-link"
                href="{{url_for('map.maps')}}">
                Map
              </a>
              <a 
                class="nav-item nav-link"
                href="{{url_for('todo.ycd')}}">
                YouCanDo
              </a>
            </div>
              <!-- Navbar Right Side -->
            <div class="navbar-nav ms-auto">
              {% if current_user.is_authenticated %}
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('posts.new_post')}} ">
                  Create
                </a>
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('users.logout')}} ">
                  Logout
                </a>
              {% else %}
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('users.login')}} ">
                  Login
                </a>
                <a
                  class="nav-item nav-link"
                  href="{{ url_for('users.register')}} ">
                  Join
                </a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <div class="banner">
        <div class="wrapper">
            <div class="banner_text">
                <h3>Importance of Tree to reduce  air  pollution in Dhaka</h3>
            </div>
        </div>
    </div>

    <!-- banner end -->
  <div class="container">
    <div class="row">
      <div class="col">
        <h2>IMPORTANCE OF TREE PLANTATION</h2>
        <p>Tree planting is recognised as one of the most engaging, environmentally-friendly activities that people can participate in to help the planet when done properly. Trees provide numerous long-term and short-term benefits. They not only look nice, but they also remove and store carbon from the atmosphere, slow heavy rain and thus reduce the risk of flooding, improve air quality, and reduce the urban heat island effect by reflecting sunlight and providing shade. Let us take a look at the long and short essay on tree plantation.</p>
        <img
        src="https://images.pexels.com/photos/4207908/pexels-photo-4207908.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260" alt="">
      </div>
    </div>
    <div class="row">
      <div class="col">
        <h2>Deforestation</h2>
        <p>The major effect of deforestation on the environment is global warming and climatic change.</p>
        <p>Cutting down trees can directly or indirectly affect human health. Due to the lack of oxygen, people can suffer from breathing problems. Deforestation destroys ecosystems that are vital to wildlife and humans alike. Lush green forests offer a home to some of the world’s most iconic wild animals, from the jaguar to the panda, along with countless diverse species of vegetation. But the importance of forests doesn’t stop there. Like the ocean, forests absorb excess atmospheric carbon dioxide, serving as a much-needed buffer against irreversible climate change. In short, forests help sustain life around the world—far beyond where their tree lines end.</p>
        <img src="https://images.pexels.com/photos/5214145/pexels-photo-5214145.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"
        alt="">
      </div>
    </div>
    <div class="row">
      <div class="col">
        <h2>How to overcome</h2>
        <p>Trees provide clean air for living beings to respire and produce energy. For a healthy life, free from suffocation and pollution, the importance of tree plantation cannot be underestimated, especially in urban areas. The importance of tree plantation is tremendous to maintain the biodiversity and balance the ecosystem. Trees provide a natural habitat for a variety of species. Rich biodiversity and a healthy ecosystem revitalize the land and life on planet earth. Trees have an important role to play in maintaining ecological balance and equilibrium. Trees help in holding the soil and binding the top fertile layer of the soil. Trees help in maintaining the hydrological cycle. They, thus, help in maintaining the monsoon cycles and rainfall patterns. Trees also help in keeping the water table level high.</p>
        <img src="https://images.pexels.com/photos/4705015/pexels-photo-4705015.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260" alt="">
      </div>
    </div>
  </div>


    <!-- footer strt -->
    <div class="footer">
        <div class="wrapper">
            <div class="footer_nav">
                <ul>
                    <li>Home</li></a></li>
                    <li>|</li>
                    <li>About Us</li>
                    <li>|</li>
                    <li>Solutions</li>
                    <li>|</li>
                    <li>Contract Us</li>
                 <p>Copyright@2022.pythonic_lava,Inc.All Rights Reserved</p>
                </ul>
            </div>
        </div>
    </div>
    <!-- 
    <!-- js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>footer end -->
</body>
</html>